apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: groovy-ingress
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - http:
        paths:
        - path: /groovy
          pathType: Prefix
          backend:
            service:
              name: buildpack-example-svc
              port:
                number: 8000
        - path: /java/gradle
          pathType: Prefix
          backend:
            service:
              name: buildpack-example-svc
              port:
                number: 8001
        - path: /java/maven
          pathType: Prefix
          backend:
            service:
              name: buildpack-example-svc
              port:
                number: 8002
        - path: /python
          pathType: Prefix
          backend:
            service:
              name: buildpack-example-svc
              port:
                number: 8003