apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: buildpack-example
  name: buildpack-example-svc
spec:
  type: ClusterIP
  ports:
  - name: groovy-spring-app
    port: 8000
    protocol: TCP
    targetPort: groovy-port
  - name: gradle-spring-app
    port: 8001
    protocol: TCP
    targetPort: gradle-port
  - name: maven-spring-app
    port: 8002
    protocol: TCP
    targetPort: maven-port
  - name: fastapi-app
    port: 8003
    protocol: TCP
    targetPort: fastapi-port
  selector:
    app: buildpack-example
