[project]
id = "com.boxboat.maven-spring-app"
name = "Maven Spring Example Application"
version = "1.0.0"

[build]
exclude = [
    "README.md",
    "target"
]

[[build.env]]
name='GOOGLE_ENTRYPOINT'
value='./mvnw spring-boot:run'